# Generated by Django 4.1.2 on 2022-10-17 21:55

from django.db import migrations


def Owners(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    flats = Flat.objects.all()
    for flat in flats.iterator():
        Owner.objects.get_or_create(
            owner=flat.owner,
            owner_pure_phone=flat.owner_pure_phone,
            owners_phonenumber=flat.owners_phonenumber
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_flat_liked_by_flat_new_building_and_more'),
    ]

    operations = [
        migrations.RunPython(Owners)
    ]
