# Generated by Django 2.2.24 on 2022-10-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20221016_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(default=False, verbose_name='Новое здание'),
        ),
    ]
