# Generated by Django 4.1.2 on 2022-10-18 07:26

from django.db import migrations


def flats_owners(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    Owners = apps.get_model('property', 'Owner')
    flats_owner = Owners.objects.all()
    for flat_owner in flats_owner.iterator():
        finded_flats = Flats.objects.filter(owner=flat_owner.owner)
        flat_owner.flats_in_use.set(finded_flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_owner_flats_in_use_alter_owner_owner_and_more'),
    ]

    operations = [
        migrations.RunPython(flats_owners)
    ]
