# Generated by Django 4.1.2 on 2022-10-18 10:57
import phonenumbers
from django.db import migrations


def phone_parse(apps, schema_editor):
    Owners = apps.get_model('property', 'Owner')
    for owner in Owners.objects.all():
        number_parse = phonenumbers.parse(owner.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(number_parse):
            pure_number = phonenumbers.format_number(number_parse,
                                            phonenumbers.PhoneNumberFormat.E164)
        else:
            pure_number = None
        owner.owner_pure_phone = pure_number
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20221018_1026'),
    ]

    operations = [
        migrations.RunPython(phone_parse),
    ]
