# Generated by Django 4.1.2 on 2022-10-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20221018_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
