# Generated by Django 4.1.2 on 2022-10-18 11:01

from django.db import migrations


def newbuilding(apps, schema_editor):
    Flats = apps.get_model('property', 'Flat')
    Flats.objects.filter(construction_year__gte=2015).update(new_building=True)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_remove_flat_owner_remove_flat_owner_pure_phone_and_more'),
    ]

    operations = [
        migrations.RunPython(newbuilding),
    ]
