# Generated by Django 2.2.24 on 2022-10-17 12:54

from django.db import migrations


def newbuilding(apps, schema_editor):
    Years = apps.get_model('property', 'Flat')
    for year in Years.objects.all().filter(construction_year__gte=2015):
        year.new_building=True
        year.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20221017_1554'),
    ]

    operations = [
        migrations.RunPython(newbuilding),
    ]
