# Generated by Django 4.1.2 on 2022-10-17 18:17
import phonenumbers
from django.db import migrations


def phone_parse(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    for flat in flats.objects.all():
        number_parse = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        pure_number = phonenumbers.format_number(number_parse,
                                        phonenumbers.PhoneNumberFormat.E164)
        flat.owner_pure_phone = pure_number
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(phone_parse),
    ]
